[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_TMDB_BASE_URL = "https://api.themoviedb.org/3"
  VITE_TMDB_BASE_URL_IMG = "https://image.tmdb.org/t/p"

[context.deploy-preview.environment]
  VITE_TMDB_BASE_URL = "https://api.themoviedb.org/3"
  VITE_TMDB_BASE_URL_IMG = "https://image.tmdb.org/t/p"

[context.branch-deploy.environment]
  VITE_TMDB_BASE_URL = "https://api.themoviedb.org/3"
  VITE_TMDB_BASE_URL_IMG = "https://image.tmdb.org/t/p"
